#Sales Records Analysis

###Author: Smaya Melgara

###Exercise 2.E Using functions for analyzing data

This notebook analyzes a small sales dataset using Python functions.

Each function takes the full dataset as its first argument.

In [2]:
sales_data = [
    ('Laptop', 'East', 1200.00),
    ('Phone', 'West', 850.00),
    ('Tablet', 'East', 400.00),
    ('Monitor', 'South', 650.00),
    ('Keyboard', 'West', 75.00),
    ('Laptop', 'South', 1150.00),
    ('Phone', 'East', 900.00),
    ('Tablet', 'West', 425.00),
    ('Monitor', 'East', 680.00),
    ('Keyboard', 'South', 80.00),
    ('Laptop', 'West', 1300.00),
    ('Phone', 'West', 820.00),
]

##Lab 1. Total sales by region

In [4]:
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

In [5]:
print(region_total(sales_data, 'East'))

print(region_total(sales_data, 'West'))

print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


##Lab 2. Count of sales by region

In [6]:
def region_count(data, region):
    return sum(1 for _, r, amt in data if r == region)

In [7]:
print(region_count(sales_data, 'East'))

print(region_count(sales_data, 'West'))

print(region_count(sales_data, 'South'))

4
5
3


##Lab 3. Average sale amount by region

In [8]:
def region_average(data, region):

    total = region_total(data, region)

    count = region_count(data, region)

    if count == 0:
        return 0

    return total / count

In [9]:
print(region_average(sales_data, 'East'))

print(region_average(sales_data, 'West'))

print(region_average(sales_data, 'South'))

print(region_average(sales_data, 'North'))

795.0
694.0
626.6666666666666
0


##Lab 4. Filter by sale amount 

In [11]:
def sales_above(data, threshold):

    return [record for record in data if record[2] > threshold]

In [12]:
results = sales_above(sales_data, 500)

for record in results:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


In [13]:
def sales_below(data, threshold):

    return [record for record in data if record[2] < threshold] 

In [14]:
results = sales_below(sales_data, 500)

for record in results:
    print(record)

('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


##Lab 5. Top and bottom sale

In [15]:
def top_sale(data):

    return max(data, key=lambda s: s[2])


def bottom_sale(data):

    return min(data, key=lambda s: s[2])

In [16]:
print(top_sale(sales_data))

print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The top sale was a Laptop in the West region for $1300.00.

The bottom sale was a Keyboard in the West region for $75.00.

##Lab 6. Apply a discount 

In [17]:
def apply_discount(data, discount_pct):

    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))

In [18]:
discounted_sales = apply_discount(sales_data, 0.15)

print("Before discount:")
for record in sales_data[:3]:
    print(record)

print()

print("After discount:")
for record in discounted_sales[:3]:
    print(record)

Before discount:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

After discount:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


##Lab 7. Unique Regions 

In [19]:
def unique_regions(data):

    return sorted(set(region for _, region, amount in data))

In [20]:
print(unique_regions(sales_data))

['East', 'South', 'West']


The unique_regions function could be useful in a longer analysis program because it helps identify all the different regions in the dataset without repeating any region names. 

This pattern can be used to find unique categories, such as product names, customer types, departments, states, or payment methods. Once you know the unique values, you can use them to group data, create summaries, or build reports.

##Lab 8. Region Summary

In [22]:
def region_summary(data, region):

    region_data = [record for record in data if record[1] == region]

    total = region_total(data, region)
    count = region_count(data, region)
    average = region_average(data, region)
    top = top_sale(region_data)

    print("===", region, "Region ===")
    print("Records:", count)
    print("Total Sales: $" + format(total, ",.2f"))
    print("Average Sale: $" + format(average, ",.2f"))
    print("Top Sale:", top[0], "— $" + format(top[2], ",.2f"))

##Lab 9. Full Summary 

In [23]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)
    print()

=== East Region ===
Records: 4
Total Sales: $3,180.00
Average Sale: $795.00
Top Sale: Laptop — $1,200.00

=== South Region ===
Records: 3
Total Sales: $1,880.00
Average Sale: $626.67
Top Sale: Laptop — $1,150.00

=== West Region ===
Records: 5
Total Sales: $3,470.00
Average Sale: $694.00
Top Sale: Laptop — $1,300.00



In this set of labs, I learned how to use Python functions to analyze a dataset. I practiced creating functions that calculate totals, counts, averages, filtered records, discounts, and summaries.

I also learned how to reuse functions inside other functions instead of rewriting the same logic. This makes the code cleaner and easier to understand. These labs showed how functions can help organize data analysis and make it easier to create reports from a dataset.